version: "3.3"

services:
  web:
    build: .
    command: >
      sh -c "python main.py"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - ./.env

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/code
    command: >
      sh -c "aio_celery worker src.celery_stuff.app:app"

    env_file:
      - ./.env
    depends_on:
      - web
    stdin_open: true
